{"uuid": "c3865fb2-cfda-4d59-bf5c-e23c9a4ad04e", "children": ["f4c570df-1948-4427-9586-0b9ac48c5ffc", "837f1fb2-2ee6-4d88-be55-392e5992b116", "dcdcf074-274e-43ce-9732-bdc1dad04528", "86c9068d-7fe1-4074-952e-235bb6fd326a", "6945d334-097a-4ed2-9826-f100106c34b9", "550d4e2a-9901-428c-b495-b5b69cffb465", "544ae88b-171b-404f-8013-20da7f8a2cdf", "6e05bd9a-71ce-4a5a-bce5-71b178860350", "2cce1f31-5b2d-4cf1-8849-a41909968707", "dd720ae8-5349-4a74-80a8-807bc018c7a5", "a2c4fcb8-d83b-4271-9010-954732ed2b26", "93b667ba-896c-46ab-8f0b-b6c7b2edbade", "42fe352e-49da-409e-9e0b-dee0342a9084", "83effeff-dbfe-4b1f-bea5-f442251f94d3", "d6017804-bdc1-4565-a505-fcf9fe56e4e3", "17ace32b-f0c4-4ba0-be5f-8e3c094874ca", "a2492e7e-aa01-407e-9723-904a3817295f", "c89018f4-3398-4e3b-b0ff-8dff45dc614a", "00e17fcc-0986-4088-8e3c-e86b2b16fc55"], "befores": [{"name": "system_login", "status": "failed", "statusDetails": {"message": "Failed: 接口请求异常，可能是request的连接数过多或请求速度过快导致程序报错！\n", "trace": "  File \"A:\\anaconda\\envs\\test\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"A:\\anaconda\\envs\\test\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"A:\\anaconda\\envs\\test\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"A:\\anaconda\\envs\\test\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"A:\\anaconda\\envs\\test\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"A:\\anaconda\\envs\\test\\lib\\site-packages\\_pytest\\fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"E:\\TTbookshop\\testcase\\conftest.py\", line 30, in system_login\n    RequestBase().specification_yaml(api_info[0][0], api_info[0][1])\n  File \"E:\\TTbookshop\\base\\apiutil.py\", line 98, in specification_yaml\n    res = self.run.run_main(name=api_name, url=url, case_name=case_name, header=header, method=method,\n  File \"E:\\TTbookshop\\common\\sendrequest.py\", line 155, in run_main\n    response = self.send_request(method=method,\n  File \"E:\\TTbookshop\\common\\sendrequest.py\", line 111, in send_request\n    pytest.fail(\"接口请求异常，可能是request的连接数过多或请求速度过快导致程序报错！\")\n  File \"A:\\anaconda\\envs\\test\\lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "attachments": [{"name": "接口名称：用户登录", "source": "8ef09c0c-9832-48e2-a259-ce58bc4745f7-attachment.txt", "type": "text/plain"}, {"name": "接口地址：http://127.0.0.1:8787/dar/user/login", "source": "d724fd39-fcb6-4153-9c53-ab8f308fb3bc-attachment.txt", "type": "text/plain"}, {"name": "请求方法：post", "source": "2936b745-c9d0-4b84-acb5-44e5cd4e5979-attachment.txt", "type": "text/plain"}, {"name": "请求头：{'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'}", "source": "792128d5-b207-40d4-a529-f68110df1013-attachment.txt", "type": "text/plain"}, {"name": "测试用例名称：用户名和密码正确登录验证", "source": "1b300fce-3df6-4cff-b4b6-ef655749991f-attachment.txt", "type": "text/plain"}, {"name": "请求参数", "source": "a4c66081-30e3-4722-8818-04272b5dab50-attachment.txt", "type": "text/plain"}], "start": 1754423357885, "stop": 1754423359925}], "start": 1754423357885, "stop": 1754423365119}